export const DEFAULT_REDACTION_KEYS = [
  'password',
  'apiKey',
  'api_key',
  'secret',
  'authorization',
  'bearer',
  'token',
  'creditCard',
  'credit_card',
  'cvv',
  'ssn',
  'email',
];

export const PRICING_PLANS = [
  {
    id: 'free',
    name: 'Free',
    subtitle: 'For individual developers prototyping agents',
    price: 0,
    interval: '/month',
    features: [
      '1 project',
      '1,000 runs / month',
      '7-day retention',
      'Basic run inspection',
      'Community support',
      'Standard rate limits',
    ],
    limits: {
      projects: 1,
      runs: 1000,
      retentionDays: 7,
      analyses: 20,
    },
    popular: false,
  },
  {
    id: 'developer',
    name: 'Developer',
    subtitle: 'For solo founders and production AI builders',
    price: 19,
    interval: '/month',
    features: [
      '5 projects',
      '25,000 runs / month',
      '30-day retention',
      'Run replay mode',
      'Run comparison & divergence detection',
      'AI failure analysis (Groq/Llama)',
      'Configurable data redaction',
      'Priority email support',
    ],
    limits: {
      projects: 5,
      runs: 25000,
      retentionDays: 30,
      analyses: 500,
    },
    popular: true,
  },
  {
    id: 'pro',
    name: 'Pro',
    subtitle: 'For fast-growing AI startups and engineering teams',
    price: 49,
    interval: '/month',
    features: [
      '20 projects',
      '250,000 runs / month',
      '90-day retention',
      'Advanced latency & token analytics',
      'Automated regression alerts',
      'Extended AI investigation budget',
      'Export traces to CSV & JSON',
      'Dedicated Slack channel',
    ],
    limits: {
      projects: 20,
      runs: 250000,
      retentionDays: 90,
      analyses: 2500,
    },
    popular: false,
  },
  {
    id: 'team',
    name: 'Team',
    subtitle: 'For organizations with high-volume agent workloads',
    price: 149,
    interval: '/month',
    features: [
      'Unlimited projects',
      '1,000,000+ runs / month',
      '365-day retention',
      'Role-based access controls (RBAC)',
      'Custom redaction pipelines',
      'Self-hosted trace proxy option',
      'Custom SLA & 99.9% uptime',
      'Dedicated customer engineer',
    ],
    limits: {
      projects: 999,
      runs: 1000000,
      retentionDays: 365,
      analyses: 10000,
    },
    popular: false,
  },
];

export const SYSTEM_STATUSES = [
  { name: 'Trace Ingestion API', status: 'Operational', latency: '42ms', uptime: '99.98%' },
  { name: 'Dashboard & Web App', status: 'Operational', latency: '28ms', uptime: '100%' },
  { name: 'Event Replay Engine', status: 'Operational', latency: '19ms', uptime: '99.99%' },
  { name: 'AI Analysis Service (Groq / Llama)', status: 'Operational', latency: '310ms', uptime: '99.95%' },
  { name: 'PostgreSQL Database Cluster', status: 'Operational', latency: '12ms', uptime: '100%' },
];
