import { Run } from '../types';

export const DEMO_RUN_FAILED_1842: Run = {
  id: 'run_1842_failed',
  projectId: 'proj_default',
  agentName: 'Customer Support Agent',
  status: 'FAILED',
  startedAt: '2026-10-01T14:32:18.000Z',
  completedAt: '2026-10-01T14:32:21.024Z',
  durationMs: 3024,
  totalTokens: 4821,
  inputTokens: 3840,
  outputTokens: 981,
  estimatedCost: 0.0184,
  model: 'llama-3.3-70b-versatile',
  environment: 'production',
  tags: ['refunds', 'tool-calling', 'customer-ops'],
  errorMessage: 'HTTP 401 Unauthorized during tool execution: process_refund',
  isDemo: true,
  events: [
    {
      id: 'ev_1842_01',
      runId: 'run_1842_failed',
      timestamp: '2026-10-01T14:32:18.000Z',
      offsetMs: 0,
      type: 'USER_INPUT',
      title: 'User request received',
      status: 'OK',
      data: {
        userInput: 'I need a full refund for order #ORD-9821. It arrived broken and unsealed.',
      },
    },
    {
      id: 'ev_1842_02',
      runId: 'run_1842_failed',
      timestamp: '2026-10-01T14:32:18.142Z',
      offsetMs: 142,
      durationMs: 339,
      type: 'MODEL_CALL',
      title: 'Model Call: llama-3.3-70b-versatile',
      status: 'OK',
      data: {
        modelCall: {
          model: 'llama-3.3-70b-versatile',
          inputTokens: 482,
          outputTokens: 76,
          temperature: 0.2,
          latencyMs: 339,
          promptPreview: 'System: You are an autonomous refunds support agent. Analyze customer requests and invoke payment tools safely...',
          responsePreview: 'Action: search_customer({"email": "pamarthikrishnasayee@gmail.com", "orderId": "ORD-9821"})',
        },
      },
    },
    {
      id: 'ev_1842_03',
      runId: 'run_1842_failed',
      timestamp: '2026-10-01T14:32:18.481Z',
      offsetMs: 481,
      durationMs: 648,
      type: 'TOOL_CALL',
      title: 'Tool: search_customer',
      status: 'OK',
      statusCode: 200,
      data: {
        toolCall: {
          toolName: 'search_customer',
          arguments: {
            email: 'pamarthikrishnasayee@gmail.com',
            orderId: 'ORD-9821',
          },
          response: {
            customerId: 'cus_9938210',
            tier: 'enterprise',
            lifetimeValue: '$14,200',
            accountStatus: 'active',
          },
          status: 200,
          latencyMs: 648,
        },
      },
    },
    {
      id: 'ev_1842_04',
      runId: 'run_1842_failed',
      timestamp: '2026-10-01T14:32:19.129Z',
      offsetMs: 1129,
      durationMs: 754,
      type: 'TOOL_CALL',
      title: 'Tool: get_order',
      status: 'OK',
      statusCode: 200,
      data: {
        toolCall: {
          toolName: 'get_order',
          arguments: {
            orderId: 'ORD-9821',
            customerId: 'cus_9938210',
          },
          response: {
            orderId: 'ORD-9821',
            totalAmount: 189.50,
            currency: 'USD',
            status: 'delivered',
            paymentMethod: 'pm_stripe_card_4242',
            refundable: true,
          },
          status: 200,
          latencyMs: 754,
        },
      },
    },
    {
      id: 'ev_1842_05',
      runId: 'run_1842_failed',
      timestamp: '2026-10-01T14:32:19.883Z',
      offsetMs: 1883,
      durationMs: 264,
      type: 'TOOL_CALL',
      title: 'Tool: process_refund',
      status: 'ERROR',
      statusCode: 401,
      data: {
        toolCall: {
          toolName: 'process_refund',
          arguments: {
            orderId: 'ORD-9821',
            amount: 189.50,
            reason: 'damaged_in_transit',
            idempotencyKey: 'idem_9821_f498',
          },
          response: {
            error: 'Unauthorized',
            code: 'EXPIRED_PAYMENT_SESSION_TOKEN',
            message: 'Integration token scope has expired or is invalid for finance:refund operations',
          },
          status: 401,
          latencyMs: 264,
        },
      },
    },
    {
      id: 'ev_1842_06',
      runId: 'run_1842_failed',
      timestamp: '2026-10-01T14:32:20.147Z',
      offsetMs: 2147,
      durationMs: 280,
      type: 'TOOL_CALL',
      title: 'Retry: process_refund',
      status: 'ERROR',
      statusCode: 401,
      data: {
        toolCall: {
          toolName: 'process_refund',
          arguments: {
            orderId: 'ORD-9821',
            amount: 189.50,
            reason: 'damaged_in_transit',
            idempotencyKey: 'idem_9821_f498_retry1',
          },
          response: {
            error: 'Unauthorized',
            code: 'EXPIRED_PAYMENT_SESSION_TOKEN',
            message: 'Integration token scope has expired or is invalid for finance:refund operations',
          },
          status: 401,
          latencyMs: 280,
        },
      },
    },
    {
      id: 'ev_1842_07',
      runId: 'run_1842_failed',
      timestamp: '2026-10-01T14:32:20.427Z',
      offsetMs: 2427,
      type: 'ERROR',
      title: 'Error: ToolExecutionFailed',
      status: 'ERROR',
      statusCode: 401,
      data: {
        error: {
          errorType: 'ToolExecutionFailed',
          statusCode: 401,
          message: 'Repeated authentication failure on financial gateway tool [process_refund]. Aborting run.',
          culpritTool: 'process_refund',
        },
      },
    },
    {
      id: 'ev_1842_08',
      runId: 'run_1842_failed',
      timestamp: '2026-10-01T14:32:21.024Z',
      offsetMs: 3024,
      type: 'FINAL_RESPONSE',
      title: 'Agent Termination / Fallback Response',
      status: 'ERROR',
      data: {
        finalResponse: 'I am unable to process your refund at this moment due to a payment service authentication failure. Our human support team has been flagged with reference incident #INC-1842.',
      },
    },
  ],
};

export const DEMO_RUN_SUCCESS_1841: Run = {
  id: 'run_1841_success',
  projectId: 'proj_default',
  agentName: 'Customer Support Agent',
  status: 'SUCCESS',
  startedAt: '2026-10-01T14:30:05.000Z',
  completedAt: '2026-10-01T14:30:07.110Z',
  durationMs: 2110,
  totalTokens: 3120,
  inputTokens: 2510,
  outputTokens: 610,
  estimatedCost: 0.0118,
  model: 'llama-3.3-70b-versatile',
  environment: 'production',
  tags: ['refunds', 'tool-calling', 'customer-ops'],
  isDemo: true,
  events: [
    {
      id: 'ev_1841_01',
      runId: 'run_1841_success',
      timestamp: '2026-10-01T14:30:05.000Z',
      offsetMs: 0,
      type: 'USER_INPUT',
      title: 'User request received',
      status: 'OK',
      data: {
        userInput: 'I need a full refund for order #ORD-9820. Item received damaged.',
      },
    },
    {
      id: 'ev_1841_02',
      runId: 'run_1841_success',
      timestamp: '2026-10-01T14:30:05.138Z',
      offsetMs: 138,
      durationMs: 332,
      type: 'MODEL_CALL',
      title: 'Model Call: llama-3.3-70b-versatile',
      status: 'OK',
      data: {
        modelCall: {
          model: 'llama-3.3-70b-versatile',
          inputTokens: 460,
          outputTokens: 74,
          temperature: 0.2,
          latencyMs: 332,
          promptPreview: 'System: You are an autonomous refunds support agent...',
          responsePreview: 'Action: search_customer({"email": "pamarthikrishnasayee@gmail.com", "orderId": "ORD-9820"})',
        },
      },
    },
    {
      id: 'ev_1841_03',
      runId: 'run_1841_success',
      timestamp: '2026-10-01T14:30:05.470Z',
      offsetMs: 470,
      durationMs: 625,
      type: 'TOOL_CALL',
      title: 'Tool: search_customer',
      status: 'OK',
      statusCode: 200,
      data: {
        toolCall: {
          toolName: 'search_customer',
          arguments: {
            email: 'pamarthikrishnasayee@gmail.com',
            orderId: 'ORD-9820',
          },
          response: {
            customerId: 'cus_9938210',
            tier: 'enterprise',
            lifetimeValue: '$14,200',
            accountStatus: 'active',
          },
          status: 200,
          latencyMs: 625,
        },
      },
    },
    {
      id: 'ev_1841_04',
      runId: 'run_1841_success',
      timestamp: '2026-10-01T14:30:06.095Z',
      offsetMs: 1095,
      durationMs: 685,
      type: 'TOOL_CALL',
      title: 'Tool: get_order',
      status: 'OK',
      statusCode: 200,
      data: {
        toolCall: {
          toolName: 'get_order',
          arguments: {
            orderId: 'ORD-9820',
            customerId: 'cus_9938210',
          },
          response: {
            orderId: 'ORD-9820',
            totalAmount: 189.50,
            currency: 'USD',
            status: 'delivered',
            paymentMethod: 'pm_stripe_card_4242',
            refundable: true,
          },
          status: 200,
          latencyMs: 685,
        },
      },
    },
    {
      id: 'ev_1841_05',
      runId: 'run_1841_success',
      timestamp: '2026-10-01T14:30:06.780Z',
      offsetMs: 1780,
      durationMs: 330,
      type: 'TOOL_CALL',
      title: 'Tool: process_refund',
      status: 'OK',
      statusCode: 200,
      data: {
        toolCall: {
          toolName: 'process_refund',
          arguments: {
            orderId: 'ORD-9820',
            amount: 189.50,
            reason: 'damaged_in_transit',
            idempotencyKey: 'idem_9820_a112',
          },
          response: {
            refundId: 'ref_9820_ok_129',
            status: 'succeeded',
            amountRefunded: 189.50,
            currency: 'USD',
            receiptUrl: 'https://pay.stripe.com/receipts/r_9820',
          },
          status: 200,
          latencyMs: 330,
        },
      },
    },
    {
      id: 'ev_1841_06',
      runId: 'run_1841_success',
      timestamp: '2026-10-01T14:30:07.110Z',
      offsetMs: 2110,
      type: 'FINAL_RESPONSE',
      title: 'Final Agent Response',
      status: 'OK',
      data: {
        finalResponse: 'Your refund of $189.50 for order #ORD-9820 has been processed successfully to your original payment card. Reference: ref_9820_ok_129.',
      },
    },
  ],
};

export const DEMO_RUN_SQL_FAILED: Run = {
  id: 'run_1843_sql_error',
  projectId: 'proj_default',
  agentName: 'Analytics SQL Copilot',
  status: 'FAILED',
  startedAt: '2026-10-01T15:10:00.000Z',
  completedAt: '2026-10-01T15:10:02.400Z',
  durationMs: 2400,
  totalTokens: 2940,
  inputTokens: 2400,
  outputTokens: 540,
  estimatedCost: 0.0092,
  model: 'llama-3.3-70b-versatile',
  environment: 'production',
  tags: ['analytics', 'sql', 'reporting'],
  errorMessage: 'PostgreSQL error: column "users.created_at" must appear in the GROUP BY clause or be used in an aggregate function',
  isDemo: true,
  events: [
    {
      id: 'ev_sql_01',
      runId: 'run_1843_sql_error',
      timestamp: '2026-10-01T15:10:00.000Z',
      offsetMs: 0,
      type: 'USER_INPUT',
      title: 'User Query',
      status: 'OK',
      data: {
        userInput: 'Show total revenue grouped by country and user creation date for September 2026',
      },
    },
    {
      id: 'ev_sql_02',
      runId: 'run_1843_sql_error',
      timestamp: '2026-10-01T15:10:00.250Z',
      offsetMs: 250,
      type: 'MODEL_CALL',
      title: 'Model Call: Query Generator',
      status: 'OK',
      data: {
        modelCall: {
          model: 'llama-3.3-70b-versatile',
          inputTokens: 1850,
          outputTokens: 240,
          latencyMs: 650,
          responsePreview: 'SELECT country, created_at, SUM(amount) FROM payments JOIN users ON users.id = payments.user_id GROUP BY country',
        },
      },
    },
    {
      id: 'ev_sql_03',
      runId: 'run_1843_sql_error',
      timestamp: '2026-10-01T15:10:00.900Z',
      offsetMs: 900,
      durationMs: 420,
      type: 'TOOL_CALL',
      title: 'Tool: execute_warehouse_sql',
      status: 'ERROR',
      statusCode: 400,
      data: {
        toolCall: {
          toolName: 'execute_warehouse_sql',
          arguments: {
            query: 'SELECT country, created_at, SUM(amount) FROM payments JOIN users ON users.id = payments.user_id GROUP BY country',
          },
          response: {
            error: 'SQLSTATE 42803',
            message: 'column "users.created_at" must appear in the GROUP BY clause or be used in an aggregate function',
          },
          status: 400,
          latencyMs: 420,
        },
      },
    },
    {
      id: 'ev_sql_04',
      runId: 'run_1843_sql_error',
      timestamp: '2026-10-01T15:10:01.320Z',
      offsetMs: 1320,
      type: 'ERROR',
      title: 'SQL Syntax & Grouping Failure',
      status: 'ERROR',
      statusCode: 400,
      data: {
        error: {
          errorType: 'QueryExecutionException',
          statusCode: 400,
          message: 'Query failed with PostgreSQL 42803: unaggregated column created_at missing from GROUP BY',
          culpritTool: 'execute_warehouse_sql',
        },
      },
    },
  ],
};

export const INITIAL_SAMPLE_RUNS: Run[] = [
  DEMO_RUN_FAILED_1842,
  DEMO_RUN_SUCCESS_1841,
  DEMO_RUN_SQL_FAILED,
];
